export {hasValidRowTotal} from './hasValidRowTotal.js'
export {hasValidTotal} from './hasValidTotal.js'
export {hasValidColumnTotal} from './hasValidColumnTotal.js'
export {hasValidBoxTotal} from './hasValidBoxTotal.js'
export {getRow} from './getRow.js'
export {getColumn} from './getColumn.js'
export {getBox} from './getBox.js'
