export {default as hasValidRowTotal} from './hasValidRowTotal.js'
export {default as hasValidTotal} from './hasValidTotal.js'
export {default as hasValidColumnTotal} from './hasValidColumnTotal.js'
export {default as hasValidBoxTotal} from './hasValidBoxTotal.js'
export {default as getRow} from './getRow.js'
export {default as getColumn} from './getColumn.js'
export {default as getBox} from './getBox.js'
